services:
  digital-twin:
    build:
      context: ./docker
      dockerfile: Dockerfile
      network: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: rp2040-digital-twin
    security_opt:
      - label:disable
    volumes:
      - ./firmware:/workspace/firmware:ro,z
      - ./renode:/workspace/renode:ro,z
      - ./output:/workspace/output:z
    entrypoint: ["/bin/bash", "/workspace/scripts/entrypoint.sh"]

  digital-twin-metrics:
    build:
      context: ./docker
      dockerfile: Dockerfile
      network: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
    container_name: rp2040-digital-twin-metrics
    security_opt:
      - label:disable
    volumes:
      - ./firmware:/workspace/firmware:ro,z
      - ./renode:/workspace/renode:ro,z
      - ./output:/workspace/output:z
    entrypoint: ["/bin/bash", "-c", "/workspace/scripts/build_firmware.sh && /workspace/scripts/run_metrics.sh"]
    profiles:
      - metrics
